# Generated by Django 4.1.5 on 2023-01-06 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Image height cannot be smaller than 1')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Image width cannot be smaller than 1')]),
        ),
    ]
