# Generated by Django 4.1.5 on 2023-01-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_image_alter_image_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
    ]
